### ISSUE TITLE
Issue in running tin node.

### ISSUE THREAD

**Issue by kumart4** [marcgille/thing-it-node#18]
So let me start from beginning, i tried and followed the steps to install thing-it-node on RPi3 running Raspbian.
After installation to test the Auto-Discovery module and my HUE bulb, following the instructions in the github.

Create a directory hue-test
As it supports auto discovery run tin init
Executing tin-init gives the following error:
"tin run
No options file in start directory [/Users/kumarrounak/hue-test]. Using defaults.

[thing-it-node]

Firmware : 0.21.57

Protocol : http

Port : 3001

Node Configurations Directory: /Users/kumarrounak/hue-test/configurations

Simulated : true

Log Level : debug

10/19/2017 4:41:57 PM INFO NodeManager ===> Scanning directory [/usr/local/lib/node_modules/thing-it-node/lib/default-devices] for Device Plugins:

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-virtual-device]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [virtual-device/button].

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [virtual-device/knob].

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [virtual-device/slider].

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [virtual-device/switch].

10/19/2017 4:41:57 PM INFO NodeManager ===> Scanning directory [/usr/local/lib/node_modules/thing-it-node/lib/../node_modules] for Device Plugins:

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-aircable]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [aircable/airCableSmartDimmer].

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-ar-drone]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [ar-drone/ardroneBluetoothLE].

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [ar-drone/ardroneWifi].

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-art-net]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [art-net/artNetUniverse].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [art-net/fogMachine].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [art-net/movingHead].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [art-net/rgbLed].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [art-net/simpleLight].

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-atlas-scientific]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [atlas-scientific/pHMeter].

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-bacnet]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [bacnet/bacNetDevice].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/analogInput].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/analogValue].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/binaryInput].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/binaryValue].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/jalousie].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/light].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/multiStateInput].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/multiStateValue].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/roomControl].

10/19/2017 4:41:57 PM INFO NodeManager Loading Unit Plugin [bacnet/thermostat].

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-blueid]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [blueid/blueIdAdmin].

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [blueid/blueIdDoor].

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-browser]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [browser/browser].

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-btle-heart-rate-monitor]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [btle-heart-rate-monitor/btleHeartRateMonitor].

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-camera]:

10/19/2017 4:41:57 PM INFO NodeManager Loading Device Plugin [camera/usbCamera].

10/19/2017 4:41:57 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-chp]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [chp/chp].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-ecobee]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [ecobee/electricMeter].

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [ecobee/gasMeter].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-enlighted]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [enlighted/enlightedDevice].

10/19/2017 4:41:58 PM INFO NodeManager Loading Unit Plugin [enlighted/area].

10/19/2017 4:41:58 PM INFO NodeManager Loading Unit Plugin [enlighted/fixture].

10/19/2017 4:41:58 PM INFO NodeManager Loading Unit Plugin [enlighted/group].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-foscam]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [foscam/camera].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-halytech]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [halytech/dataLogger].

10/19/2017 4:41:58 PM INFO NodeManager Loading Unit Plugin [halytech/channel].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-helbio]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [helbio/fuelCellCoGen].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-hibox]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [hibox/HiBoxTV].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-ibeacon]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [ibeacon/beaconScanner].

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [ibeacon/iBeacon].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-itach]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [itach/emotivaRm100].

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [itach/iRobotRoombaRemote].

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [itach/irSniffer].

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [itach/tvRemote].

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [itach/yamahaHTR6130].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-kidde]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [kidde/smokeDetector].

10/19/2017 4:41:58 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-kisi]:

10/19/2017 4:41:58 PM INFO NodeManager Loading Device Plugin [kisi/kisiAdmin].

10/19/2017 4:42:00 PM INFO NodeManager Loading Device Plugin [kisi/kisiDoor].

10/19/2017 4:42:00 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-microcontroller]:

10/19/2017 4:42:00 PM INFO NodeManager Loading Device Plugin [microcontroller/arduino].

10/19/2017 4:42:00 PM INFO NodeManager Loading Device Plugin [microcontroller/microcontroller].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/button].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/co2].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/encoder].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/fan].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/gate].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/lcd].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/led].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/multi].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/photocell].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/pixel].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/potentiometer].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/proximity].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/relay].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/rgbLed].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/servo].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/switch].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [microcontroller/thermostat].

10/19/2017 4:42:00 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-occupancy-sensor]:

10/19/2017 4:42:00 PM INFO NodeManager Loading Device Plugin [occupancy-sensor/occupancySensor].

10/19/2017 4:42:00 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-osram-lightify]:

10/19/2017 4:42:00 PM INFO NodeManager Loading Device Plugin [osram-lightify/lightifyGateway].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [osram-lightify/led].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [osram-lightify/lightBulb].

10/19/2017 4:42:00 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-osram-sympholight]:

10/19/2017 4:42:00 PM INFO NodeManager Loading Device Plugin [osram-sympholight/sympholightServer].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [osram-sympholight/daliGroup].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [osram-sympholight/dmxMovingHead].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [osram-sympholight/dmxRgbLight].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [osram-sympholight/dmxTemperatureLight].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [osram-sympholight/pirSensor].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [osram-sympholight/scene].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [osram-sympholight/singleDmxChannel].

10/19/2017 4:42:00 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-philips-hue]:

10/19/2017 4:42:00 PM INFO NodeManager Loading Device Plugin [philips-hue/hueBridge].

10/19/2017 4:42:00 PM INFO NodeManager Loading Unit Plugin [philips-hue/lightBulb].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [philips-hue/livingColorLamp].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-plugwise]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [plugwise/motionSensor].

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [plugwise/outlet].

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [plugwise/switch].

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [plugwise/thermostat].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-radio-thermostat]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [radio-thermostat/radioThermostat].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-rfid-sensor]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [rfid-sensor/rfidSensor].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-safe-plug]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [safe-plug/loadControlDevice].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-smart-meter]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [smart-meter/smartMeter].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-sonos]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [sonos/sonos].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-swann]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [swann/camera].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-temperature-alert]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [temperature-alert/measurementUnit].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [temperature-alert/temperatureSensor].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-test]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [test/testDevice].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [test/testActor].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [test/testSensor].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-ti-sensortag]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [ti-sensortag/tiSensorTag].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-weather]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [weather/weather].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-wind-turbine]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [wind-turbine/windTurbine].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-wtec]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [wtec/smartengine].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [wtec/fixture].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [wtec/location].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [wtec/locationInformation].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [wtec/locationLightControl].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-xiaomi-smart-plant-monitor]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [xiaomi-smart-plant-monitor/plantMonitor].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-yamaha]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [yamaha/yamaha].

10/19/2017 4:42:01 PM INFO NodeManager Processing Device Plugin Directory [thing-it-device-z-wave]:

10/19/2017 4:42:01 PM INFO NodeManager Loading Device Plugin [z-wave/zWaveNetwork].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [z-wave/binaryPowerSwitch].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [z-wave/genericDevice].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [z-wave/homeSecuritySensor].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [z-wave/multilevelSceneSwitch].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [z-wave/multilevelSensor].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [z-wave/routingBinarySensor].

10/19/2017 4:42:01 PM INFO NodeManager Loading Unit Plugin [z-wave/thermostatGeneric].

10/19/2017 4:42:01 PM INFO NodeManager ===> Scanning directory [/usr/local/lib/node_modules/thing-it-node/lib/../../../node_modules] for Device Plugins:

10/19/2017 4:42:01 PM DEBUG NodeManager Plugins loaded.

10/19/2017 4:42:01 PM INFO NodeManager ===> Scanning directory [/Users/kumarrounak/hue-test/configurations] for Node Configurations:

Cannot start node: { Error: ENOENT: no such file or directory, scandir '/Users/kumarrounak/hue-test/configurations'

at Object.fs.readdirSync (fs.js:911:18)

at NodeManager.NodeManager.loadNodeConfigurations (/usr/local/lib/node_modules/thing-it-node/lib/node.js:231:23)

at NodeManager.NodeManager.initialize (/usr/local/lib/node_modules/thing-it-node/lib/node.js:131:30)

at NodeManager.NodeManager.bootstrapNode (/usr/local/lib/node_modules/thing-it-node/lib/node.js:94:14)

at Object.bootstrap (/usr/local/lib/node_modules/thing-it-node/lib/node.js:28:28)

at Server.<anonymous> (/usr/local/lib/node_modules/thing-it-node/bin/thing-it-node.js:313:26)

at Object.onceWrapper (events.js:314:30)

at emitNone (events.js:105:13)

at Server.emit (events.js:207:7)

at emitListeningNT (net.js:1371:10)
errno: -2,

code: 'ENOENT',

syscall: 'scandir',

path: '/Users/kumarrounak/hue-test/configurations' }"

In another attempt, i tried downloading the xiaomi-plant-monitor example and run it. This seems to run but gives following message:

"10/19/2017 4:52:12 PM DEBUG Node[The Node] No Auto-Discovery started for simulated gateways.

10/19/2017 4:52:12 PM INFO NodeManager Node started in proxy mode against server https://www.thing-it.com.

10/19/2017 4:52:12 PM INFO NodeManager Attempt to initialize Reverse Proxy

10/19/2017 4:52:12 PM INFO NodeManager Initializing Web Socket for event dispatching at /events

10/19/2017 4:52:12 PM INFO NodeManager Initialize REST API for server.

10/19/2017 4:52:12 PM INFO NodeManager Communication initialized.

10/19/2017 4:52:12 PM INFO NodeManager Heartbeat started.

10/19/2017 4:52:12 PM INFO NodeManager Starting Configuration Manager.

Boot Directory: undefined

Configuration Directory: /Users/kumarrounak/xiaomi-smart-plant-monitor-test

Reboot Cmd: undefined

Starting Bluetooth.

10/19/2017 4:52:12 PM INFO Node[The Node] Data started.

10/19/2017 4:52:12 PM INFO Device[Plant Sensor Rhododendron] Starting Device [Plant Sensor Rhododendron]

10/19/2017 4:52:12 PM DEBUG Node[The Node] Publish Device Operational State Change Plant Sensor Rhododendron { state: 'normal' }

10/19/2017 4:52:12 PM DEBUG Node[The Node] Publish Device State Change Plant Sensor Rhododendron {}

10/19/2017 4:52:12 PM DEBUG Node[The Node] Publish Device State Change Plant Sensor Rhododendron {}

10/19/2017 4:52:12 PM INFO Device[Plant Sensor Rhododendron] Device [Plant Sensor Rhododendron] started.

10/19/2017 4:52:12 PM INFO Node[The Node] Devices started.

10/19/2017 4:52:12 PM INFO Node[The Node] Event Processors started.

10/19/2017 4:52:12 PM INFO Node[The Node] Jobs activated.

10/19/2017 4:52:12 PM INFO Node[The Node] Node [The Node] booted.

10/19/2017 4:52:27 PM INFO NodeManager (Re)try initial NS connection for https://www.thing-it.com/proxies/f6c40500-b370-11e7-af6d-15eaef156a28

10/19/2017 4:52:28 PM INFO NodeManager Server notified { paired: true }

10/19/2017 4:52:28 PM INFO NodeManager Reverse Proxy prepared on server.

10/19/2017 4:52:30 PM INFO NodeManager Reverse Proxy connected.

10/19/2017 4:52:32 PM DEBUG Node[The Node] Publish Device State Change Plant Sensor Rhododendron { illumination: 10000,

temperature: 18,

humidity: 50,

fertility: 5.100006103515625 }"

But when i try to open localhost:3001

it open a webpage like attached.

Also, I tried downloading the thing-it-node preloaded RPI3 image, but when i try to browse to localhost:3001 it opens a webpage asking for login but when i try to provide my thing-it.com username and password it does not login giving authorisation error.

Can you please help. Also, if there is any documentation to help start the setup and on writing configuration it will help. I want to write plugins for the devices i own at home.

**Comment by neilepalmer** [comment]
Hey - thanks for this.  I'll take a look at tin-init and see where the issue is.  Also, for the second part, your screenshot doesn't seem to be attached - can you reattach/resend please?

**Comment by kumart4** [comment]
Thanks, I have attached the missing screenshot.
<img width="1438" alt="screen shot 2017-10-19 at 4 53 58 pm" src="https://user-images.githubusercontent.com/32681471/31991007-488fe02e-b994-11e7-9991-c1654eaea94a.png">

**Comment by neilepalmer** [comment]
What version of node/npm are you using?

**Comment by kumart4** [comment]
Kumars-iMac:cgi-bin kumarrounak$ npm -v
5.4.2
Kumars-iMac:cgi-bin kumarrounak$ node -v
v8.7.0
Kumars-iMac:cgi-bin kumarrounak$

**Comment by neilepalmer** [comment]
Thanks.  Right now we're not supporting anything above the current node LTS - so v6.x.  I'm running v6.9 personally.  Might want to try install NVM on the Pi so you can easily download and install/switch between different versions.  Let me know how you get on.

**Comment by kumart4** [comment]
Even downgrading to 6.9 I still get same set of errors.

**Comment by neilepalmer** [comment]
Well that's a bummer.  Let me kick some things around my side and get back to you

**Comment by kumart4** [comment]
Any luck on your end replicating the issue?
I am still facing same set of error.
Alternatively, I also tried the prebuilt image for Pi available at thing-it.com
but when I try to open the localhost:3001 it opens a webpage asking for login but when i try to provide my thing-it.com username and password it does not login giving authorisation error.

Doesn't seems to be moving.

**Comment by neilepalmer** [comment]
Sorry - haven't had a chance to track it down.  Am on the road this week, will give it a shot over the weekend and report back

**Comment by jonwrede** [comment]
I have the same error in current release

> Loading failed for the <script> with source “cordova.js”.
Loading failed for the <script> with source “js/thing-it-mobile-external.min.js”.
Loading failed for the <script> with source “js/plotly-latest.min.js”.
Loading failed for the <script> with source “js/app.js”.

If I look at the www folder in the source I can only find app.min.js. If i then replace the js/app.js with js/app.min.js. And there is a wired testDate.js file which seams to indicate a dev branch got merged before being tested. I guess I expected a mature automation solution for building (factory) automation so that means i need to look further. Or maybe you can provide an earlier verion thats stable.
